[ 
  [ [ true, "PINK:ANC01:ACT0:POSITION", "Channel", 1, 1, "51,153,255", null ],
    [ true, "PINK:ANC01:ACT0:CMD:TARGET", "Channel", 1, 1, "51,204,0", null ] ],
  [ [ "1", null, null, null, null, null, null, null ],
    [ "2", null, null, null, null, null, null, null ],
    [ "3", null, null, null, null, null, null, null ],
    [ "4", null, null, null, null, null, null, null ],
    [ "5", null, null, null, null, null, null, null ] ],
  [ [ ] ],
  [ [ "", 1000, 100 ],
    [ "", "" ] ]  
]